### PR TITLE
Here's "My Pokedex"!

### PR DESCRIPTION
**Pull request by thecodercody**
Enjoy!

### CODE REVIEW

**Comment by thecodercody** [comment]
I've made it better :-)

**Comment by thecodercody** [comment]
Even better now.

**Comment by thecodercody** [comment]
fixed right sidebar scrolling issue

**Comment by thecodercody** [comment]
finishing touches

**Comment by bmatto** [comment]
This is great - and hilarious.  Thank you very much for your time.  Nothing like building a pokedex amiright?

**Comment by thecodercody** [comment]
Hahaha - I did enjoy myself; it was actually really fun to build.  In my
most recent entrepreneurial venture, I had a colorful, cartoony brand
mascot character, Dr. Bones (see below), so it was totally up my alley.  I
love this kind of theme - this, happy go-lucky, child-like, fun theme.
Anyway, thanks for meeting with me and for the project!  I look forward to
hearing from you!
                          [image: Inline image 1]

**Pull request closed without merging**
